apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.mysql.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.mysqlRootPassword | b64enc | quote }}
  mysql-user: {{ .Values.mysql.mysqlUser | b64enc | quote }}
  mysql-password: {{ .Values.mysql.mysqlPassword | b64enc | quote }}
  mysql-database: {{ .Values.mysql.mysqlDatabase | b64enc | quote }}
